### ISSUE TITLE
Changing array structure

### ISSUE THREAD

**Issue by lukasoppermann** [daylerees/sanitizer#15]
Hey, I do have an issue with the array structure.

When I give the following array into the sanitizer

``` php
['some.dot.array' => 'value']
```

It correctly does the sanitization with the provided array

``` php
  ["data.attributes.type"]=> [
    [0]=> "strtoupper"
    [1]=> "trim"
  ]
```

The problem is that the returned array is:

``` php
[
   'some' => [
      'dot' =>  [
          'array' => 'VALUE'
      ]
   ]
]
```

However I would need and expect:

``` php
['some.dot.array' => 'VALUE']
```

Did I miss something?

**Comment by vladimirardelean** [comment]
It uses the function array_get in  the Illuminate/support helpers library, that means that the dot stands for nested arrays. You could not have an array key with dot because it belives that must check for ['same' => ['dot' => ['array' => '']]]. However the sanitization rules are not supporting nested arrays (will be nice).

Please see bellow the Laravel documentation on array_get: 

> array_get()
> 
> The array_get function retrieves a value from a deeply nested array using "dot" notation:
> 
> ```
> $array = ['products' => ['desk' => ['price' => 100]]];
> 
> $value = array_get($array, 'products.desk');
> 
> ```
> // ['price' => 100]
> The array_get function also accepts a default value, which will be returned if the specific key is not found:
