### ISSUE TITLE
Available rules

### ISSUE THREAD

**Issue by ilvalerione** [daylerees/sanitizer#16]
Hello, congratulations for the code syntax, great job! :+1: 

Have you a list of base rules available in standard package installation?

Thanks

**Comment by mikemclin** [comment]
There are no base rules included.  As you can see here: https://github.com/daylerees/sanitizer/blob/master/src/Sanitizer.php#L167, any callable can be a filter rule.  Therefore any PHP function can be a filter rule.  The code example rules `trim`, `strtolower`, etc are available because they are available as functions in PHP.  So, that means you could also use things like `ucwords` or `number_format` without having to add any additional rules.

Even though it says `"Rules can contain either callable functions"` towards the beginning of the README page, it didn't click with me either, and I had to dip into the codebase to see what was happening.
